[package]
name = "rs-proxy"
version = "0.2.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
log = "0.4"
env_logger = "0.8.4"
clap = { version = "3.1.18", features = ["derive"] }
toml = "0.4.5"
serde_derive = "1.0.32"
serde = "1.0.32"
thiserror = "1.0.31"
anyhow = "1.0.57"